# RealToxicityPrompts dataset configuration
dataset:
  name: "allenai/real-toxicity-prompts"
  split: "train"
  max_prompts: 5000  # Increased from 1000 to 5000 for more comprehensive evaluation
  shuffle_seed: 42
  
  # Filtering strategy
  filtering:
    strategy: "toxicity_threshold"
    toxicity_threshold: 0.3  # Lowered from 0.4 to get more diverse prompts
    metrics: ["toxicity", "severe_toxicity"]
    
    # Alternative filtering options
    # strategy: "range"
    # min_toxicity: 0.2
    # max_toxicity: 0.9
    
    # strategy: "top_k"
    # k: 5000
    # sort_by: "toxicity"
    
    # strategy: "random"
    # sample_size: 5000

# Dataset processing
processing:
  min_prompt_length: 10
  max_prompt_length: 200
  remove_duplicates: true
  normalize_whitespace: true
  
# Caching options
caching:
  use_cache: true
  cache_dir: "datasets/cache"
  cache_name: "real_toxicity_filtered_5000"
  force_regenerate: false

# Alternative dataset sources
alternatives:
  # Use cached dataset
  # strategy: "cached"
  # cache_path: "datasets/high_toxicity_prompts.json"
  
  # Use custom prompt set
  # strategy: "custom"
  # prompts_file: "prompts/custom_toxic_prompts.txt"
  
  # Generate new dataset using dataset_generator
  # strategy: "generated"
  # generator_config:
  #   model_name: "EleutherAI/pythia-410m"
  #   num_samples: 5000
  #   toxicity_threshold: 0.3 