# Standard visualization configuration for Enhanced Toxicity Evaluation Pipeline
visualization:
  enabled: true
  
  # Plot types to generate
  plot_types:
    scatter_plots: true
    distribution_plots: true
    comparison_plots: true
    correlation_matrix: true
    progression_plots: true
    summary_plots: true
  
  # Plot settings
  plot_settings:
    # Figure settings
    figure_size: [12, 8]
    dpi: 300
    format: "png"  # png, pdf, svg
    
    # Style settings
    style: "seaborn-v0_8"
    color_palette: "husl"
    font_size: 12
    title_size: 14
    label_size: 12
    tick_size: 10
    legend_size: 10
    
    # Grid and layout
    show_grid: true
    grid_alpha: 0.3
    tight_layout: true
    
  # Scatter plot settings
  scatter_plots:
    alpha: 0.6
    point_size: 20
    show_regression: true
    show_diagonal: true
    equal_aspect: true
    max_models_per_row: 3
    
  # Distribution plot settings
  distribution_plots:
    bins: 30
    show_kde: true
    show_statistics: true
    density: true
    
  # Comparison plot settings
  comparison_plots:
    show_zero_line: true
    improvement_threshold: 0.0
    color_improved: "green"
    color_regressed: "red"
    
  # Correlation matrix settings
  correlation_matrix:
    mask_upper_triangle: true
    annotate: true
    cmap: "coolwarm"
    center: 0
    square: true
    linewidths: 0.5
    fmt: "%.3f"
    
  # Progression plot settings
  progression_plots:
    sort_by_epoch: true
    show_statistics: true
    max_epochs_per_row: 3
    
  # Summary plot settings
  summary_plots:
    include_statistics: true
    show_confidence_intervals: false
    error_bars: "std"  # std, sem, ci
    
  # Output settings
  output:
    save_individual_plots: true
    save_summary_report: true
    save_plot_data: true
    compress_plots: false
    
    # File naming
    naming:
      scatter_prefix: "scatter_"
      distribution_prefix: "distribution_"
      comparison_prefix: "comparison_"
      correlation_prefix: "correlation_"
      progression_prefix: "progression_"
      summary_prefix: "summary_"
      
    # Report settings
    report:
      include_statistics: true
      include_sample_data: true
      max_sample_rows: 100
      include_configuration: true
      
  # Performance settings
  performance:
    parallel_plotting: false  # Not implemented yet
    memory_limit_mb: 1024
    timeout_seconds: 300
    
  # Error handling
  error_handling:
    continue_on_error: true
    log_errors: true
    fallback_plots: true
    min_data_points: 10 