# Configuration for Pythia-410M IRL

dataset:
  original_model_name: "EleutherAI/pythia-410m"
  detoxified_model_name: "ajagota71/pythia-410m-detox-epoch-100"
  original_dataset_path: "${hydra:runtime.cwd}/datasets/pythia-410m-original.json"
  detoxified_dataset_path: "${hydra:runtime.cwd}/datasets/pythia-410m-detoxified.json"

model:
  reward_model_base: "EleutherAI/pythia-410m"
  use_half_precision: true
  num_unfrozen_layers: 1

training:
  irl_method: "max_margin"
  learning_rate: 5e-6
  epochs: 15
  batch_size: 4
  eval_interval: 3

output:
  repo_name_prefix: "irl-pythia-410m"